module.exports = [
  'Apartment Building',
  'Apartelle',
  'Boarding House',
  'Bungalow',
  'Cabin',
  'Commercial Building',
  'Condominium',
  'Cottage',
  'Detached House',
  'Dormitory',
  'Duplex',
  'Farmhouse',
  'Fourplex',
  'Hotel',
  'Industrial Building',
  'Mansion',
  'Mixed-Use Building',
  'Motel',
  'Office Building',
  'Resort',
  'Retail Building',
  'Row House',
  'Semi-Detached House',
  'Shophouse',
  'Single-Family House',
  'Split-Level House',
  'Three-Storey House',
  'Townhouse',
  'Triplex',
  'Two-Storey House',
  'Villa',
  'Warehouse',
];
