module.exports = [
  'Studio',
  'Standard Room',
  '1 Bedroom',
  '2 Bedroom',
  '3 Bedroom',
  'Loft',
  'Penthouse',
  'Hotel Room',
  'Deluxe Room',
  'Suite',
  'Executive Suite',
  'Presidential Suite',
  'Retail Space',
  'Office Space',
  'Warehouse',
  'Storage Unit',
  'Showroom',
  'Restaurant Space',
  'Kiosk',
  'Function Room',
  'Conference Room',
  'Meeting Room',
  'Event Hall',
  'Parking Slot',
  'Motorcycle Parking',
  'Storage Locker',
];
